// ==WindhawkMod==
// @id              ai-usage-pill
// @name            AI Usage Pill
// @description     Pílula na borda esquerda da tela com o uso de sessão e semanal do Claude, Codex e outros, via ai-usagebar
// @version         1.0.0
// @author          gustavofrdev
// @github          https://github.com/gustavofrdev
// @include         explorer.exe
// @architecture    x86-64
// @compilerOptions -lgdiplus -lgdi32 -lshell32 -lruntimeobject -lole32 -loleaut32
// ==/WindhawkMod==

// ==WindhawkModReadme==
/*
# AI Usage Pill

Mostra uma pílula pequena, colada na borda esquerda do monitor principal, com
o uso de cada provedor de IA: a barra grossa é a sessão de 5 horas e a fina é
a semanal. A cor é a da marca (Claude laranja, Codex verde).

Os números vêm do [ai-usagebar](https://github.com/akitaonrails/ai-usagebar).
Por padrão o mod roda o ai-usagebar de dentro do WSL, então usa o login que
já existe lá. Se instalar a versão Windows, troque o comando nas configurações.

A pílula não recebe clique: o mouse passa através dela. Quando a atualização
falha, ela fica apagada com um ponto âmbar e mantém os últimos números; o
motivo aparece no log do mod.
*/
// ==/WindhawkModReadme==

// ==WindhawkModSettings==
/*
- command: wsl.exe -e sh -lc "ai-usagebar usage --json"
  $name: Comando
  $description: Comando que imprime o JSON do ai-usagebar (usage --json). O padrão roda o ai-usagebar do WSL por um shell de login, para achar o ~/.local/bin no PATH. Com a versão Windows, informe o caminho do ai-usagebar.exe seguido de usage --json.
- refreshMinutes: 5
  $name: Intervalo de atualização (minutos)
  $description: Os endpoints da Anthropic e da OpenAI bloqueiam consultas com menos de 5 minutos de intervalo; abaixo disso os números podem ficar mais atrasados, não menos.
- leftOffset: 12
  $name: Distância da esquerda (px)
  $description: Espaço entre a borda esquerda da taskbar e a pílula, em pixels de tela a 100% de escala. Aumente se ela cobrir algo da taskbar.
- opacity: 100
  $name: Opacidade (%)
- vendors:
  - - id: anthropic
      $name: Provedor
    - color: "#D97757"
      $name: Cor
  - - id: openai
      $name: Provedor
    - color: "#10A37F"
      $name: Cor
  $name: Provedores
  $description: Ordem e cor de cada linha. Use o id do ai-usagebar (anthropic, openai, cursor, copilot...).
*/
// ==/WindhawkModSettings==

// Generated by tools/bundle.sh from src/. Edit the files in src/, not this one.

#include <windows.h>
#include <gdiplus.h>
#include <shellapi.h>
#undef GetObject
#include <winrt/Windows.Data.Json.h>
#include <winrt/Windows.Foundation.Collections.h>

#include <algorithm>
#include <atomic>
#include <cmath>
#include <functional>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

// ---- src/common.h ----

namespace {

namespace json = winrt::Windows::Data::Json;

constexpr int kSessionWindowSecs = 18000;
constexpr int kWeeklyWindowSecs = 604800;
constexpr int kUnknownPercent = -1;
constexpr int kWarnPercent = 90;
constexpr DWORD kCommandTimeoutMs = 30000;
constexpr size_t kMaxCommandOutput = 1 << 20;
constexpr UINT kSnapshotChangedMsg = WM_APP + 1;
constexpr wchar_t kWindowClassName[] = L"AiUsagePillWindow";
constexpr wchar_t kInstanceMutexName[] = L"Local\\AiUsagePillInstance";

struct VendorUsage {
    std::wstring vendorId;
    int sessionPercent = kUnknownPercent;
    int weeklyPercent = kUnknownPercent;
};

struct VendorStyle {
    std::wstring vendorId;
    Gdiplus::ARGB color;
};

struct PillRow {
    std::wstring vendorId;
    Gdiplus::ARGB color;
    int sessionPercent;
    int weeklyPercent;
};

struct PillSettings {
    std::wstring command;
    int refreshMinutes;
    int leftOffset;
    int opacityPercent;
    std::vector<VendorStyle> vendorStyles;
};

PillSettings defaultPillSettings() {
    return {L"wsl.exe -e sh -lc \"ai-usagebar usage --json\"", 5, 12, 100,
            {{L"anthropic", 0xFFD97757}, {L"openai", 0xFF10A37F}}};
}

std::wstring utf8ToWide(const std::string& utf8Text) {
    int length = MultiByteToWideChar(CP_UTF8, 0, utf8Text.data(),
                                     static_cast<int>(utf8Text.size()), nullptr, 0);
    std::wstring wideText(length, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, utf8Text.data(), static_cast<int>(utf8Text.size()),
                        wideText.data(), length);
    return wideText;
}

std::string wideToUtf8(const std::wstring& wideText) {
    int length = WideCharToMultiByte(CP_UTF8, 0, wideText.data(), static_cast<int>(wideText.size()),
                                     nullptr, 0, nullptr, nullptr);
    std::string utf8Text(length, '\0');
    WideCharToMultiByte(CP_UTF8, 0, wideText.data(), static_cast<int>(wideText.size()),
                        utf8Text.data(), length, nullptr, nullptr);
    return utf8Text;
}

// Parses "#RRGGBB" (or "RRGGBB") into an opaque GDI+ ARGB.
// Example: parseHexColor(L"#D97757") == 0xFFD97757
Gdiplus::ARGB parseHexColor(const std::wstring& hexColor) {
    std::wstring digits = hexColor.starts_with(L"#") ? hexColor.substr(1) : hexColor;
    bool isHex = digits.size() == 6 && digits.find_first_not_of(L"0123456789abcdefABCDEF") ==
                                           std::wstring::npos;
    if (!isHex) {
        throw std::invalid_argument("Color '" + wideToUtf8(hexColor) +
                                    "' rejected; expected #RRGGBB, e.g. #D97757");
    }
    return 0xFF000000 | static_cast<Gdiplus::ARGB>(std::stoul(digits, nullptr, 16));
}

int clampPercent(double rawPercent) {
    if (std::isnan(rawPercent) || rawPercent < 0) {
        return kUnknownPercent;
    }
    return static_cast<int>(std::lround(std::min(rawPercent, 100.0)));
}

// Pairs each configured vendor (in settings order) with its latest usage.
// Example: buildPillRows(settings.vendorStyles, snapshot.usages)
std::vector<PillRow> buildPillRows(const std::vector<VendorStyle>& styles,
                                   const std::vector<VendorUsage>& usages) {
    std::vector<PillRow> rows;
    for (const VendorStyle& style : styles) {
        auto match = std::find_if(usages.begin(), usages.end(), [&](const VendorUsage& usage) {
            return usage.vendorId == style.vendorId;
        });
        bool found = match != usages.end();
        rows.push_back({style.vendorId, style.color, found ? match->sessionPercent : kUnknownPercent,
                        found ? match->weeklyPercent : kUnknownPercent});
    }
    return rows;
}

class UniqueHandle {
public:
    explicit UniqueHandle(HANDLE handle = nullptr) : handle_(handle) {}
    ~UniqueHandle() { reset(); }
    UniqueHandle(const UniqueHandle&) = delete;
    UniqueHandle& operator=(const UniqueHandle&) = delete;
    HANDLE get() const { return handle_; }

    void reset(HANDLE handle = nullptr) {
        if (handle_ != nullptr && handle_ != INVALID_HANDLE_VALUE) {
            CloseHandle(handle_);
        }
        handle_ = handle;
    }

private:
    HANDLE handle_;
};

[[noreturn]] void throwLastError(const std::string& operation, const std::wstring& context) {
    throw std::runtime_error(operation + " failed with Win32 error " +
                             std::to_string(GetLastError()) + " for '" + wideToUtf8(context) + "'");
}

}  // namespace

// ---- src/hidden_process_runner.h ----

namespace {

// Runs a command line with no console window and returns its stdout. Only the
// pipe and NUL handles are inherited, so explorer.exe handles never leak into it.
// Example: std::string json = HiddenProcessRunner(30000, stopEvent).run(L"wsl.exe -e ai-usagebar usage --json");
class HiddenProcessRunner {
public:
    HiddenProcessRunner(DWORD timeoutMs, HANDLE cancelEvent)
        : timeoutMs_(timeoutMs), cancelEvent_(cancelEvent) {}

    std::string run(const std::wstring& commandLine) const {
        UniqueHandle readEnd;
        UniqueHandle writeEnd;
        createStdoutPipe(readEnd, writeEnd, commandLine);
        UniqueHandle process(launchHidden(commandLine, writeEnd.get()));
        writeEnd.reset();
        std::string output = collectOutput(readEnd.get(), process.get(), commandLine);
        requireZeroExitCode(process.get(), commandLine);
        return output;
    }

private:
    // Any failure while reading (such as output over kMaxCommandOutput) must
    // not leave the child running after the mod gives up on it.
    std::string collectOutput(HANDLE readEnd, HANDLE process, const std::wstring& commandLine) const {
        std::string output;
        ULONGLONG deadline = GetTickCount64() + timeoutMs_;
        try {
            while (!hasExited(process, deadline, commandLine)) {
                drainAvailable(readEnd, output);
            }
            drainAvailable(readEnd, output);
        } catch (...) {
            TerminateProcess(process, 1);
            throw;
        }
        return output;
    }

    static SECURITY_ATTRIBUTES inheritableAttributes() {
        return {sizeof(SECURITY_ATTRIBUTES), nullptr, TRUE};
    }

    static void createStdoutPipe(UniqueHandle& readEnd, UniqueHandle& writeEnd,
                                 const std::wstring& commandLine) {
        SECURITY_ATTRIBUTES attributes = inheritableAttributes();
        HANDLE readRaw = nullptr;
        HANDLE writeRaw = nullptr;
        if (!CreatePipe(&readRaw, &writeRaw, &attributes, 0)) {
            throwLastError("CreatePipe", commandLine);
        }
        readEnd.reset(readRaw);
        writeEnd.reset(writeRaw);
        SetHandleInformation(readRaw, HANDLE_FLAG_INHERIT, 0);
    }

    static HANDLE launchHidden(const std::wstring& commandLine, HANDLE stdoutWrite) {
        SECURITY_ATTRIBUTES attributes = inheritableAttributes();
        UniqueHandle nullDevice(CreateFileW(L"NUL", GENERIC_READ | GENERIC_WRITE,
                                            FILE_SHARE_READ | FILE_SHARE_WRITE, &attributes,
                                            OPEN_EXISTING, 0, nullptr));
        HANDLE inherited[2] = {stdoutWrite, nullDevice.get()};
        SIZE_T listSize = 0;
        InitializeProcThreadAttributeList(nullptr, 1, 0, &listSize);
        std::vector<BYTE> listBuffer(listSize);
        auto attributeList = reinterpret_cast<LPPROC_THREAD_ATTRIBUTE_LIST>(listBuffer.data());
        InitializeProcThreadAttributeList(attributeList, 1, 0, &listSize);
        UpdateProcThreadAttribute(attributeList, 0, PROC_THREAD_ATTRIBUTE_HANDLE_LIST, inherited,
                                  sizeof(inherited), nullptr, nullptr);
        HANDLE process = createProcess(commandLine, stdoutWrite, nullDevice.get(), attributeList);
        DeleteProcThreadAttributeList(attributeList);
        return process;
    }

    static HANDLE createProcess(const std::wstring& commandLine, HANDLE stdoutWrite,
                                HANDLE nullDevice, LPPROC_THREAD_ATTRIBUTE_LIST attributeList) {
        STARTUPINFOEXW startup{};
        startup.StartupInfo.cb = sizeof(startup);
        startup.StartupInfo.dwFlags = STARTF_USESTDHANDLES;
        startup.StartupInfo.hStdInput = nullDevice;
        startup.StartupInfo.hStdOutput = stdoutWrite;
        startup.StartupInfo.hStdError = nullDevice;
        startup.lpAttributeList = attributeList;
        PROCESS_INFORMATION info{};
        std::wstring mutableLine = commandLine;
        DWORD flags = CREATE_NO_WINDOW | EXTENDED_STARTUPINFO_PRESENT;
        if (!CreateProcessW(nullptr, mutableLine.data(), nullptr, nullptr, TRUE, flags, nullptr,
                            nullptr, &startup.StartupInfo, &info)) {
            throwLastError("CreateProcessW (expected an executable such as wsl.exe)", commandLine);
        }
        CloseHandle(info.hThread);
        return info.hProcess;
    }

    bool hasExited(HANDLE process, ULONGLONG deadline, const std::wstring& commandLine) const {
        HANDLE waitHandles[2] = {process, cancelEvent_};
        switch (WaitForMultipleObjects(2, waitHandles, FALSE, 50)) {
            case WAIT_OBJECT_0:
                return true;
            case WAIT_OBJECT_0 + 1:
                abortProcess(process, "was canceled because the mod is stopping", commandLine);
            default:
                break;
        }
        if (GetTickCount64() >= deadline) {
            abortProcess(process, "timed out after " + std::to_string(timeoutMs_) + " ms",
                         commandLine);
        }
        return false;
    }

    [[noreturn]] static void abortProcess(HANDLE process, const std::string& reason,
                                          const std::wstring& commandLine) {
        TerminateProcess(process, 1);
        throw std::runtime_error("Command '" + wideToUtf8(commandLine) + "' " + reason);
    }

    static void drainAvailable(HANDLE readEnd, std::string& output) {
        char chunk[4096];
        DWORD available = 0;
        DWORD bytesRead = 0;
        while (PeekNamedPipe(readEnd, nullptr, 0, nullptr, &available, nullptr) && available > 0 &&
               ReadFile(readEnd, chunk, sizeof(chunk), &bytesRead, nullptr) && bytesRead > 0) {
            output.append(chunk, bytesRead);
        }
        if (output.size() > kMaxCommandOutput) {
            throw std::runtime_error("Command output has " + std::to_string(output.size()) +
                                     " bytes; expected at most " + std::to_string(kMaxCommandOutput));
        }
    }

    static void requireZeroExitCode(HANDLE process, const std::wstring& commandLine) {
        DWORD exitCode = 0;
        GetExitCodeProcess(process, &exitCode);
        if (exitCode != 0) {
            throw std::runtime_error("Command '" + wideToUtf8(commandLine) + "' exited with code " +
                                     std::to_string(exitCode) + "; expected 0");
        }
    }

    DWORD timeoutMs_;
    HANDLE cancelEvent_;
};

}  // namespace

// ---- src/usage_report_parser.h ----

namespace {

// Turns `ai-usagebar usage --json` output into one VendorUsage per ready vendor.
// This is the only place that touches the WinRT JSON API.
// Example: std::vector<VendorUsage> usages = UsageReportParser().parse(jsonText);
class UsageReportParser {
public:
    std::vector<VendorUsage> parse(const std::string& utf8Json) const {
        json::JsonObject root{nullptr};
        if (!json::JsonObject::TryParse(utf8ToWide(utf8Json), root) || !root.HasKey(L"entries")) {
            throw std::runtime_error("ai-usagebar output rejected: expected a JSON object with an "
                                     "'entries' array, received: " + utf8Json.substr(0, 120));
        }
        std::vector<VendorUsage> usages;
        for (const json::IJsonValue& entryValue : root.GetNamedArray(L"entries")) {
            appendIfReady(entryValue, usages);
        }
        return usages;
    }

private:
    static void appendIfReady(const json::IJsonValue& entryValue, std::vector<VendorUsage>& usages) {
        if (entryValue.ValueType() != json::JsonValueType::Object) {
            return;
        }
        json::JsonObject entry = entryValue.GetObject();
        if (readString(entry, L"status") != L"ready") {
            return;
        }
        VendorUsage usage{readString(entry, L"id")};
        json::JsonArray metrics = entry.GetNamedArray(L"metrics", json::JsonArray());
        for (const json::IJsonValue& metricValue : metrics) {
            assignMetric(metricValue, usage);
        }
        usages.push_back(usage);
    }

    static void assignMetric(const json::IJsonValue& metricValue, VendorUsage& usage) {
        if (metricValue.ValueType() != json::JsonValueType::Object) {
            return;
        }
        json::JsonObject metric = metricValue.GetObject();
        double windowSecs = readNumber(metric, L"window_secs");
        if (std::isnan(windowSecs)) {
            return;
        }
        int percent = clampPercent(readNumber(metric, L"percent"));
        switch (static_cast<int>(windowSecs)) {
            case kSessionWindowSecs:
                usage.sessionPercent = percent;
                break;
            case kWeeklyWindowSecs:
                usage.weeklyPercent = percent;
                break;
            default:
                break;
        }
    }

    static std::wstring readString(const json::JsonObject& object, const wchar_t* key) {
        json::IJsonValue value = object.GetNamedValue(key, json::JsonValue::CreateNullValue());
        bool isString = value.ValueType() == json::JsonValueType::String;
        return isString ? std::wstring(value.GetString()) : std::wstring();
    }

    static double readNumber(const json::JsonObject& object, const wchar_t* key) {
        json::IJsonValue value = object.GetNamedValue(key, json::JsonValue::CreateNullValue());
        bool isNumber = value.ValueType() == json::JsonValueType::Number;
        return isNumber ? value.GetNumber() : std::nan("");
    }
};

}  // namespace

// ---- src/usage_poller.h ----

namespace {

struct UsageSnapshot {
    std::vector<VendorUsage> usages;
    bool stale = true;
};

// Thread-safe holder of the latest usage: the poller writes, the window reads.
// Example: store.publishSuccess(usages); UsageSnapshot current = store.read();
class UsageSnapshotStore {
public:
    void publishSuccess(std::vector<VendorUsage> usages) {
        std::lock_guard<std::mutex> lock(mutex_);
        snapshot_.usages = std::move(usages);
        snapshot_.stale = false;
    }

    // Keeps the last known numbers so the pill stays readable while dimmed.
    void publishFailure() {
        std::lock_guard<std::mutex> lock(mutex_);
        snapshot_.stale = true;
    }

    UsageSnapshot read() const {
        std::lock_guard<std::mutex> lock(mutex_);
        return snapshot_;
    }

private:
    mutable std::mutex mutex_;
    UsageSnapshot snapshot_;
};

// Background thread that refreshes the store right away and then every
// refreshMinutes, until stop() is called.
// Example: UsagePoller poller(command, 2, store, [] { repaintPill(); }); poller.start();
class UsagePoller {
public:
    UsagePoller(std::wstring command, int refreshMinutes, UsageSnapshotStore& store,
                std::function<void()> onPublished)
        : command_(std::move(command)),
          intervalMs_(static_cast<DWORD>(refreshMinutes) * 60000),
          store_(store),
          onPublished_(std::move(onPublished)),
          stopEvent_(CreateEventW(nullptr, TRUE, FALSE, nullptr)) {}

    ~UsagePoller() { stop(); }

    void start() { worker_ = std::thread(&UsagePoller::runLoop, this); }

    // Also cancels a command that is still running, so explorer.exe never waits
    // for the full command timeout when the mod is unloaded.
    void stop() {
        SetEvent(stopEvent_.get());
        if (worker_.joinable()) {
            worker_.join();
        }
    }

private:
    // An exception escaping a std::thread calls std::terminate and would take
    // explorer.exe down, so a failed COM setup is logged and ends the thread.
    void runLoop() {
        try {
            winrt::init_apartment(winrt::apartment_type::multi_threaded);
        } catch (const winrt::hresult_error& error) {
            Wh_Log(L"COM apartment setup failed: %s", error.message().c_str());
            return;
        }
        do {
            refreshOnce();
        } while (WaitForSingleObject(stopEvent_.get(), intervalMs_) == WAIT_TIMEOUT);
        winrt::uninit_apartment();
    }

    void refreshOnce() {
        try {
            HiddenProcessRunner runner(kCommandTimeoutMs, stopEvent_.get());
            store_.publishSuccess(UsageReportParser().parse(runner.run(command_)));
        } catch (const std::exception& error) {
            Wh_Log(L"Usage refresh failed: %S", error.what());
            store_.publishFailure();
        } catch (const winrt::hresult_error& error) {
            Wh_Log(L"Usage refresh failed: %s", error.message().c_str());
            store_.publishFailure();
        }
        onPublished_();
    }

    std::wstring command_;
    DWORD intervalMs_;
    UsageSnapshotStore& store_;
    std::function<void()> onPublished_;
    UniqueHandle stopEvent_;
    std::thread worker_;
};

}  // namespace

// ---- src/brand_logo_paths.h ----

// Generated by tools/svg_to_logo.py from assets/*.svg (ai-usagebar icons, MIT).
// Do not edit; change the SVG and rerun the script. 100x100 viewBox.

namespace {

constexpr float kAnthropicLogo[] = {
    0.0f, 25.7146f, 63.2153f, 1.0f, 41.4393f, 54.3917f, 1.0f, 41.7025f, 53.6226f, 1.0f, 41.4393f, 53.1976f,
    1.0f, 40.6705f, 53.1976f, 1.0f, 38.0394f, 53.0359f, 1.0f, 29.054f, 52.7929f, 1.0f, 21.2624f, 52.4691f,
    1.0f, 13.7134f, 52.0644f, 1.0f, 11.8111f, 51.6594f, 1.0f, 10.0303f, 49.3118f, 1.0f, 10.2123f, 48.138f,
    1.0f, 11.8111f, 47.0657f, 1.0f, 14.0981f, 47.2681f, 1.0f, 19.1574f, 47.6119f, 1.0f, 26.7467f, 48.138f,
    1.0f, 32.2516f, 48.4618f, 1.0f, 40.4073f, 49.3118f, 1.0f, 41.7025f, 49.3118f, 1.0f, 41.8846f, 48.7857f,
    1.0f, 41.4393f, 48.4618f, 1.0f, 41.0955f, 48.138f, 1.0f, 33.243f, 42.8155f, 1.0f, 24.7432f, 37.1894f,
    1.0f, 20.2909f, 33.9513f, 1.0f, 17.8824f, 32.3119f, 1.0f, 16.6684f, 30.774f, 1.0f, 16.1422f, 27.4147f,
    1.0f, 18.328f, 25.0062f, 1.0f, 21.2624f, 25.2088f, 1.0f, 22.0112f, 25.4112f, 1.0f, 24.9861f, 27.6979f,
    1.0f, 31.3407f, 32.616f, 1.0f, 39.6381f, 38.7273f, 1.0f, 40.8525f, 39.7391f, 1.0f, 41.3381f, 39.395f,
    1.0f, 41.399f, 39.1523f, 1.0f, 40.8525f, 38.2415f, 1.0f, 36.3394f, 30.0858f, 1.0f, 31.5227f, 21.7883f,
    1.0f, 29.3775f, 18.3478f, 1.0f, 28.811f, 16.2837f, 2.0f, 28.6087f, 15.4334f, 28.4669f, 14.7252f, 28.4669f,
    13.8549f, 1.0f, 30.9563f, 10.4753f, 1.0f, 32.3321f, 10.0303f, 1.0f, 35.6515f, 10.4756f, 1.0f, 37.0479f,
    11.6897f, 1.0f, 39.112f, 16.4052f, 1.0f, 42.4513f, 23.8327f, 1.0f, 47.6321f, 33.9313f, 1.0f, 49.15f,
    36.9265f, 1.0f, 49.9594f, 39.6991f, 1.0f, 50.2632f, 40.5491f, 1.0f, 50.7894f, 40.5491f, 1.0f, 50.7894f,
    40.0632f, 1.0f, 51.2141f, 34.3766f, 1.0f, 52.0035f, 27.3944f, 1.0f, 52.7726f, 18.4087f, 1.0f, 53.0358f,
    15.8793f, 1.0f, 54.2905f, 12.8435f, 1.0f, 56.7795f, 11.2041f, 1.0f, 58.7224f, 12.135f, 1.0f, 60.3212f,
    14.422f, 1.0f, 60.0986f, 15.899f, 1.0f, 59.1474f, 22.0718f, 1.0f, 57.2857f, 31.7458f, 1.0f, 56.0713f,
    38.2218f, 1.0f, 56.7795f, 38.2218f, 1.0f, 57.5892f, 37.4121f, 1.0f, 60.8677f, 33.061f, 1.0f, 66.3723f,
    26.18f, 1.0f, 68.801f, 23.448f, 1.0f, 71.6342f, 20.4325f, 1.0f, 73.4556f, 18.9957f, 1.0f, 76.8962f,
    18.9957f, 1.0f, 79.4255f, 22.7601f, 1.0f, 78.2926f, 26.6456f, 1.0f, 74.7509f, 31.1384f, 1.0f, 71.8163f,
    34.943f, 1.0f, 67.607f, 40.6097f, 1.0f, 64.9758f, 45.1431f, 1.0f, 65.2188f, 45.5072f, 1.0f, 65.8464f,
    45.4466f, 1.0f, 75.358f, 43.4228f, 1.0f, 80.4984f, 42.4917f, 1.0f, 86.6304f, 41.4393f, 1.0f, 89.4033f,
    42.7346f, 1.0f, 89.7065f, 44.0502f, 1.0f, 88.6135f, 46.7419f, 1.0f, 82.0566f, 48.3607f, 1.0f, 74.3662f,
    49.8989f, 1.0f, 62.9118f, 52.6109f, 1.0f, 62.77f, 52.7121f, 1.0f, 62.9321f, 52.9144f, 1.0f, 68.0925f,
    53.4f, 1.0f, 70.2987f, 53.5214f, 1.0f, 75.7021f, 53.5214f, 1.0f, 85.7601f, 54.2702f, 1.0f, 88.3912f,
    56.0108f, 1.0f, 89.9697f, 58.1358f, 1.0f, 89.7065f, 59.7545f, 1.0f, 85.6589f, 61.8189f, 1.0f, 80.1949f,
    60.5236f, 1.0f, 67.4452f, 57.4881f, 1.0f, 63.0735f, 56.3952f, 1.0f, 62.4665f, 56.3952f, 1.0f, 62.4665f,
    56.7596f, 1.0f, 66.1093f, 60.3213f, 1.0f, 72.7877f, 66.3523f, 1.0f, 81.1461f, 74.1236f, 1.0f, 81.5707f,
    76.0462f, 1.0f, 80.4984f, 77.5638f, 1.0f, 79.3649f, 77.4021f, 1.0f, 72.0186f, 71.8772f, 1.0f, 69.1854f,
    69.3879f, 1.0f, 62.77f, 63.9844f, 1.0f, 62.3453f, 63.9844f, 1.0f, 62.3453f, 64.5509f, 1.0f, 63.8223f,
    66.7164f, 1.0f, 71.6342f, 78.4544f, 1.0f, 72.0389f, 82.0567f, 1.0f, 71.4725f, 83.2308f, 1.0f, 69.4487f,
    83.939f, 1.0f, 67.2222f, 83.534f, 1.0f, 62.6485f, 77.1189f, 1.0f, 57.9333f, 69.8937f, 1.0f, 54.1284f,
    63.4177f, 1.0f, 53.6631f, 63.6809f, 1.0f, 51.4167f, 87.8651f, 1.0f, 50.3644f, 89.0995f, 1.0f, 47.9356f,
    90.0303f, 1.0f, 45.9121f, 88.4924f, 1.0f, 44.8392f, 86.0031f, 1.0f, 45.9118f, 81.0852f, 1.0f, 47.2071f,
    74.6701f, 1.0f, 48.2594f, 69.5699f, 1.0f, 49.2106f, 63.2356f, 1.0f, 49.7773f, 61.131f, 1.0f, 49.7367f,
    60.9892f, 1.0f, 49.2715f, 61.0498f, 1.0f, 44.4954f, 67.607f, 1.0f, 37.23f, 77.4224f, 1.0f, 31.4825f,
    83.5746f, 1.0f, 30.1063f, 84.1211f, 1.0f, 27.7181f, 82.8864f, 1.0f, 27.9408f, 80.6805f, 1.0f, 29.2763f,
    78.7177f, 1.0f, 37.2297f, 68.5988f, 1.0f, 42.026f, 62.3248f, 1.0f, 45.1227f, 58.7025f, 1.0f, 45.1024f,
    58.176f, 1.0f, 44.9204f, 58.176f, 1.0f, 23.7917f, 71.8975f, 1.0f, 20.0274f, 72.3831f, 1.0f, 18.4083f,
    70.8655f, 1.0f, 18.6106f, 68.3761f, 1.0f, 19.3798f, 67.5664f, 1.0f, 25.7343f, 63.195f, 1.0f, 25.7146f,
    63.2153f, 3.0f};

constexpr float kOpenaiLogo[] = {
    0.0f, 83.7733f, 42.8087f, 2.0f, 84.6678f, 40.1149f, 84.9771f, 37.2613f, 84.6807f, 34.4385f, 2.0f, 84.3843f,
    31.6156f, 83.489f, 28.8885f, 82.0544f, 26.4394f, 2.0f, 77.6908f, 18.8436f, 68.9203f, 14.9365f, 60.3548f, 16.7725f,
    2.0f, 57.9831f, 14.1344f, 54.9591f, 12.1668f, 51.5864f, 11.0673f, 2.0f, 48.2137f, 9.96772f, 44.611f, 9.77498f,
    41.1402f, 10.5084f, 2.0f, 37.6694f, 11.2418f, 34.4527f, 12.8755f, 31.8132f, 15.2455f, 2.0f, 29.1736f, 17.6155f,
    27.204f, 20.6383f, 26.1024f, 24.0103f, 2.0f, 23.3212f, 24.5806f, 20.6938f, 25.738f, 18.3958f, 27.405f, 2.0f,
    16.0977f, 29.0721f, 14.1819f, 31.2104f, 12.7765f, 33.6772f, 2.0f, 8.36538f, 41.2609f, 9.3669f, 50.8267f, 15.2527f,
    57.3327f, 2.0f, 14.3549f, 60.0251f, 14.0424f, 62.8782f, 14.3361f, 65.7012f, 2.0f, 14.6298f, 68.5241f, 15.523f,
    71.2518f, 16.9558f, 73.7017f, 2.0f, 21.325f, 81.3002f, 30.1011f, 85.207f, 38.6712f, 83.3686f, 2.0f, 40.5554f,
    85.4904f, 42.8707f, 87.1858f, 45.4623f, 88.3416f, 2.0f, 48.0539f, 89.4975f, 50.8622f, 90.0871f, 53.6999f, 90.0713f,
    2.0f, 62.4793f, 90.079f, 70.2575f, 84.4114f, 72.9393f, 76.0515f, 2.0f, 75.7201f, 75.4802f, 78.347f, 74.3225f,
    80.6449f, 72.6555f, 2.0f, 82.9427f, 70.9886f, 84.8587f, 68.8507f, 86.2649f, 66.3846f, 2.0f, 90.6227f, 58.8145f,
    89.6172f, 49.3005f, 83.7733f, 42.8087f, 3.0f, 0.0f, 53.6999f, 84.8356f, 2.0f, 50.1955f, 84.8411f, 46.801f,
    83.6129f, 44.1116f, 81.3661f, 1.0f, 44.5848f, 81.098f, 1.0f, 60.5123f, 71.9043f, 2.0f, 60.9087f, 71.6718f,
    61.2379f, 71.3402f, 61.4674f, 70.942f, 2.0f, 61.6969f, 70.5439f, 61.8189f, 70.0929f, 61.8215f, 69.6333f, 1.0f,
    61.8215f, 47.1769f, 1.0f, 68.5553f, 51.072f, 2.0f, 68.6225f, 51.1063f, 68.6694f, 51.1707f, 68.6814f, 51.2456f,
    1.0f, 68.6814f, 69.854f, 2.0f, 68.6641f, 78.1208f, 61.9667f, 84.8183f, 53.6999f, 84.8356f, 3.0f, 0.0f,
    21.4977f, 71.0843f, 2.0f, 19.7402f, 68.0497f, 19.1092f, 64.4925f, 19.7156f, 61.0386f, 1.0f, 20.1885f, 61.3225f,
    1.0f, 36.1321f, 70.5165f, 2.0f, 36.5266f, 70.748f, 36.9757f, 70.87f, 37.4331f, 70.87f, 2.0f, 37.8905f,
    70.87f, 38.3396f, 70.748f, 38.7341f, 70.5165f, 1.0f, 58.21f, 59.2883f, 1.0f, 58.21f, 67.0628f, 2.0f,
    58.2081f, 67.1031f, 58.1973f, 67.1424f, 58.1782f, 67.1779f, 2.0f, 58.1591f, 67.2134f, 58.1322f, 67.2441f, 58.0996f,
    67.2678f, 1.0f, 41.9671f, 76.5722f, 2.0f, 34.798f, 80.7022f, 25.6388f, 78.2463f, 21.4977f, 71.0843f, 3.0f,
    0.0f, 17.3026f, 36.3898f, 2.0f, 19.0723f, 33.3357f, 21.8655f, 31.0062f, 25.1878f, 29.8138f, 1.0f, 25.1878f,
    48.7376f, 2.0f, 25.1818f, 49.1949f, 25.2986f, 49.6453f, 25.5261f, 50.042f, 2.0f, 25.7535f, 50.4387f, 26.0833f,
    50.7671f, 26.4809f, 50.9928f, 1.0f, 45.8622f, 62.1739f, 1.0f, 39.1283f, 66.069f, 2.0f, 39.0919f, 66.0883f,
    39.0513f, 66.0984f, 39.0101f, 66.0984f, 2.0f, 38.9689f, 66.0984f, 38.9283f, 66.0883f, 38.8919f, 66.069f, 1.0f,
    22.7908f, 56.7809f, 2.0f, 15.6359f, 52.6337f, 13.1822f, 43.4816f, 17.3026f, 36.3112f, 1.0f, 17.3026f, 36.3898f,
    3.0f, 0.0f, 72.624f, 49.2426f, 1.0f, 53.1792f, 37.9512f, 1.0f, 59.8976f, 34.0718f, 2.0f, 59.9341f,
    34.0524f, 59.9747f, 34.0423f, 60.016f, 34.0423f, 2.0f, 60.0573f, 34.0423f, 60.0979f, 34.0524f, 60.1344f, 34.0718f,
    1.0f, 76.2355f, 43.3761f, 2.0f, 78.6973f, 44.7966f, 80.7043f, 46.8882f, 82.0221f, 49.4065f, 2.0f, 83.3398f,
    51.9249f, 83.914f, 54.7661f, 83.6775f, 57.5985f, 2.0f, 83.4411f, 60.431f, 82.4038f, 63.1377f, 80.6867f, 65.4027f,
    2.0f, 78.9696f, 67.6677f, 76.6436f, 69.3975f, 73.9803f, 70.3901f, 1.0f, 73.9803f, 51.466f, 2.0f, 73.9663f,
    51.0096f, 73.834f, 50.5647f, 73.5962f, 50.1749f, 2.0f, 73.3584f, 49.7851f, 73.0234f, 49.4638f, 72.624f, 49.2426f,
    3.0f, 0.0f, 79.3261f, 39.1657f, 1.0f, 78.8529f, 38.8815f, 1.0f, 62.9411f, 29.6089f, 2.0f, 62.5442f,
    29.376f, 62.0924f, 29.2532f, 61.6322f, 29.2532f, 2.0f, 61.172f, 29.2532f, 60.7202f, 29.376f, 60.3233f, 29.6089f,
    1.0f, 40.8629f, 40.8374f, 1.0f, 40.8629f, 33.0628f, 2.0f, 40.8587f, 33.0233f, 40.8654f, 32.9834f, 40.882f,
    32.9473f, 2.0f, 40.8987f, 32.9113f, 40.9248f, 32.8803f, 40.9575f, 32.8579f, 1.0f, 57.0586f, 23.5692f, 2.0f,
    59.5263f, 22.1476f, 62.3478f, 21.458f, 65.193f, 21.5811f, 2.0f, 68.0382f, 21.7042f, 70.7896f, 22.6348f, 73.1253f,
    24.2642f, 2.0f, 75.461f, 25.8936f, 77.2845f, 28.1543f, 78.3825f, 30.782f, 2.0f, 79.4806f, 33.4097f, 79.8077f,
    36.2957f, 79.3257f, 39.1025f, 1.0f, 79.3257f, 39.1657f, 1.0f, 79.3261f, 39.1657f, 3.0f, 0.0f, 37.1888f,
    52.9484f, 1.0f, 30.455f, 49.069f, 2.0f, 30.4213f, 49.0487f, 30.3925f, 49.0212f, 30.3707f, 48.9884f, 2.0f,
    30.3488f, 48.9557f, 30.3345f, 48.9186f, 30.3286f, 48.8797f, 1.0f, 30.3286f, 30.3188f, 2.0f, 30.3323f, 27.4714f,
    31.1466f, 24.6839f, 32.6761f, 22.2822f, 2.0f, 34.2057f, 19.8805f, 36.3874f, 17.9639f, 38.9661f, 16.7564f, 2.0f,
    41.5448f, 15.549f, 44.4139f, 15.1005f, 47.2381f, 15.4636f, 2.0f, 50.0622f, 15.8267f, 52.7247f, 16.9862f, 54.9141f,
    18.8067f, 1.0f, 54.4409f, 19.0748f, 1.0f, 38.5134f, 28.2686f, 2.0f, 38.117f, 28.5011f, 37.7879f, 28.8327f,
    37.5584f, 29.2308f, 2.0f, 37.329f, 29.629f, 37.207f, 30.0799f, 37.2045f, 30.5395f, 1.0f, 37.1888f, 52.9487f,
    1.0f, 37.1888f, 52.9484f, 3.0f, 0.0f, 40.8472f, 45.0632f, 1.0f, 49.5209f, 40.0643f, 1.0f, 58.21f,
    45.0635f, 1.0f, 58.21f, 55.0615f, 1.0f, 49.5523f, 60.0608f, 1.0f, 40.8632f, 55.0615f, 1.0f, 40.8472f,
    45.0632f, 3.0f};

}  // namespace

// ---- src/brand_logo.h ----

namespace {

// Opcodes written by tools/svg_to_logo.py into the float arrays.
constexpr int kLogoMove = 0;
constexpr int kLogoLine = 1;
constexpr int kLogoCubic = 2;
constexpr int kLogoClose = 3;
constexpr float kLogoViewBox = 100.0f;

struct BrandLogoShape {
    const wchar_t* vendorId;
    const float* commands;
    size_t commandCount;
};

constexpr BrandLogoShape kBrandLogos[] = {
    {L"anthropic", kAnthropicLogo, std::size(kAnthropicLogo)},
    {L"openai", kOpenaiLogo, std::size(kOpenaiLogo)},
};

// Returns the logo drawn before a vendor, or nullptr when there is none.
// Example: if (const BrandLogoShape* logo = findBrandLogo(L"anthropic")) { ... }
const BrandLogoShape* findBrandLogo(const std::wstring& vendorId) {
    for (const BrandLogoShape& logo : kBrandLogos) {
        if (vendorId == logo.vendorId) {
            return &logo;
        }
    }
    return nullptr;
}

// Replays a generated logo into a GDI+ path scaled into a square box.
// Example: LogoPathBuilder(RectF(x, y, 16, 16), path).build(*findBrandLogo(L"openai"));
class LogoPathBuilder {
public:
    LogoPathBuilder(Gdiplus::RectF box, Gdiplus::GraphicsPath& path) : box_(box), path_(path) {}

    void build(const BrandLogoShape& logo) {
        size_t index = 0;
        while (index < logo.commandCount) {
            index = appendCommand(logo.commands, index);
        }
    }

private:
    size_t appendCommand(const float* commands, size_t index) {
        switch (static_cast<int>(commands[index])) {
            case kLogoMove:
                path_.StartFigure();
                current_ = pointAt(commands, index + 1);
                return index + 3;
            case kLogoLine:
                return appendLine(commands, index);
            case kLogoCubic:
                return appendCubic(commands, index);
            case kLogoClose:
                path_.CloseFigure();
                return index + 1;
            default:
                throw std::invalid_argument("Logo opcode " + std::to_string(commands[index]) +
                                            " at index " + std::to_string(index) +
                                            " rejected; expected 0-3 from tools/svg_to_logo.py");
        }
    }

    size_t appendLine(const float* commands, size_t index) {
        Gdiplus::PointF next = pointAt(commands, index + 1);
        path_.AddLine(current_, next);
        current_ = next;
        return index + 3;
    }

    size_t appendCubic(const float* commands, size_t index) {
        Gdiplus::PointF next = pointAt(commands, index + 5);
        path_.AddBezier(current_, pointAt(commands, index + 1), pointAt(commands, index + 3), next);
        current_ = next;
        return index + 7;
    }

    Gdiplus::PointF pointAt(const float* commands, size_t index) const {
        return {box_.X + commands[index] * box_.Width / kLogoViewBox,
                box_.Y + commands[index + 1] * box_.Height / kLogoViewBox};
    }

    Gdiplus::RectF box_;
    Gdiplus::GraphicsPath& path_;
    Gdiplus::PointF current_;
};

}  // namespace

// ---- src/pill_painter.h ----

namespace {

constexpr Gdiplus::ARGB kTrackColor = 0x38FFFFFF;
constexpr Gdiplus::ARGB kSessionTextColor = 0xF0FFFFFF;
constexpr Gdiplus::ARGB kWarnTextColor = 0xFFF87171;
constexpr Gdiplus::ARGB kWeeklyTextColor = 0xA0FFFFFF;
constexpr Gdiplus::ARGB kStaleDotColor = 0xFFF5A524;
constexpr BYTE kWeeklyBarAlpha = 0xB0;

// Pixel geometry of the pill for one DPI. Values are tuned at 96 DPI, where
// the Windows 11 taskbar is 48 px tall: vendors sit side by side in one strip.
// Example: SIZE size = PillLayout::forDpi(144).pillSize(2);
struct PillLayout {
    float scale, padding, logoSize, logoGap, barWidth, barGap, textWidth, sessionLineHeight,
        sessionBarHeight, weeklyLineHeight, weeklyBarHeight, vendorGap;

    static PillLayout forDpi(UINT dpi) {
        float s = static_cast<float>(dpi == 0 ? 96 : dpi) / 96.0f;
        return {s,      4 * s,  18 * s, 6 * s, 40 * s, 5 * s,
                48 * s, 13 * s, 5 * s,  11 * s, 3 * s, 12 * s};
    }

    float contentHeight() const { return sessionLineHeight + weeklyLineHeight; }

    float blockWidth() const { return logoSize + logoGap + barWidth + barGap + textWidth; }

    float blockLeft(size_t rowIndex) const {
        return padding + rowIndex * (blockWidth() + vendorGap);
    }

    SIZE pillSize(size_t rowCount) const {
        float gaps = rowCount > 0 ? (rowCount - 1) * vendorGap : 0;
        float width = padding * 2 + rowCount * blockWidth() + gaps;
        return {std::lround(width), std::lround(padding * 2 + contentHeight())};
    }
};

// GDI+ must be started on the thread that draws and shut down after the last
// GDI+ object is gone; declaring this first in a scope guarantees that order.
class GdiplusSession {
public:
    GdiplusSession() {
        Gdiplus::GdiplusStartupInput input;
        Gdiplus::GdiplusStartup(&token_, &input, nullptr);
    }
    ~GdiplusSession() { Gdiplus::GdiplusShutdown(token_); }
    GdiplusSession(const GdiplusSession&) = delete;
    GdiplusSession& operator=(const GdiplusSession&) = delete;

private:
    ULONG_PTR token_ = 0;
};

// Top-down 32-bit DIB selected into a memory DC, as UpdateLayeredWindow expects.
// Example: DibCanvas canvas(120, 60); painter.paint(canvas, rows, false);
class DibCanvas {
public:
    DibCanvas(int width, int height) : width_(width), height_(height) {
        BITMAPINFO info{};
        info.bmiHeader = {sizeof(BITMAPINFOHEADER), width, -height, 1, 32, BI_RGB};
        bitmap_ = CreateDIBSection(nullptr, &info, DIB_RGB_COLORS, &bits_, nullptr, 0);
        if (bitmap_ == nullptr) {
            throw std::runtime_error("CreateDIBSection rejected size " + std::to_string(width) +
                                     "x" + std::to_string(height) + "; expected positive size");
        }
        deviceContext_ = CreateCompatibleDC(nullptr);
        previousBitmap_ = SelectObject(deviceContext_, bitmap_);
    }

    ~DibCanvas() {
        SelectObject(deviceContext_, previousBitmap_);
        DeleteDC(deviceContext_);
        DeleteObject(bitmap_);
    }

    DibCanvas(const DibCanvas&) = delete;
    DibCanvas& operator=(const DibCanvas&) = delete;
    int width() const { return width_; }
    int height() const { return height_; }
    BYTE* bits() const { return static_cast<BYTE*>(bits_); }
    HDC deviceContext() const { return deviceContext_; }

private:
    int width_;
    int height_;
    void* bits_ = nullptr;
    HBITMAP bitmap_ = nullptr;
    HDC deviceContext_ = nullptr;
    HGDIOBJ previousBitmap_ = nullptr;
};

Gdiplus::ARGB withAlpha(Gdiplus::ARGB color, BYTE alpha) {
    return (color & 0x00FFFFFF) | (static_cast<Gdiplus::ARGB>(alpha) << 24);
}

std::wstring formatPercent(int percent) {
    return percent == kUnknownPercent ? L"–" : std::to_wstring(percent) + L"%";
}

void fillRoundedRect(Gdiplus::Graphics& graphics, Gdiplus::ARGB color, Gdiplus::RectF rect,
                     float radius) {
    float diameter = std::min({radius * 2, rect.Width, rect.Height});
    Gdiplus::GraphicsPath path;
    path.AddArc(rect.X, rect.Y, diameter, diameter, 180, 90);
    path.AddArc(rect.GetRight() - diameter, rect.Y, diameter, diameter, 270, 90);
    path.AddArc(rect.GetRight() - diameter, rect.GetBottom() - diameter, diameter, diameter, 0, 90);
    path.AddArc(rect.X, rect.GetBottom() - diameter, diameter, diameter, 90, 90);
    path.CloseFigure();
    Gdiplus::SolidBrush brush{Gdiplus::Color(color)};
    graphics.FillPath(&brush, &path);
}

// Draws the pill into a premultiplied ARGB canvas; knows nothing about windows.
// There is no background: the taskbar behind it already provides one.
// Example: PillPainter(PillLayout::forDpi(96)).paint(canvas, rows, false);
class PillPainter {
public:
    explicit PillPainter(PillLayout layout) : layout_(layout) {}

    void paint(DibCanvas& canvas, const std::vector<PillRow>& rows, bool stale) const {
        Gdiplus::Bitmap surface(canvas.width(), canvas.height(), canvas.width() * 4,
                                PixelFormat32bppPARGB, canvas.bits());
        Gdiplus::Graphics graphics(&surface);
        graphics.SetSmoothingMode(Gdiplus::SmoothingModeAntiAlias);
        graphics.SetTextRenderingHint(Gdiplus::TextRenderingHintAntiAlias);
        graphics.Clear(Gdiplus::Color(0, 0, 0, 0));
        for (size_t rowIndex = 0; rowIndex < rows.size(); ++rowIndex) {
            paintBlock(graphics, rows[rowIndex], layout_.blockLeft(rowIndex));
        }
        if (stale) {
            paintStaleDot(graphics, canvas);
        }
    }

private:
    void paintBlock(Gdiplus::Graphics& graphics, const PillRow& row, float left) const {
        float top = layout_.padding;
        float barsLeft = left + layout_.logoSize + layout_.logoGap;
        bool nearLimit = row.sessionPercent >= kWarnPercent;
        paintLogo(graphics, row, left, top);
        paintBar(graphics, barsLeft, top, layout_.sessionLineHeight, layout_.sessionBarHeight,
                 row.sessionPercent, row.color);
        paintText(graphics, formatPercent(row.sessionPercent), barsLeft, top,
                  layout_.sessionLineHeight, 11 * layout_.scale,
                  nearLimit ? kWarnTextColor : kSessionTextColor);
        float weeklyTop = top + layout_.sessionLineHeight;
        paintBar(graphics, barsLeft, weeklyTop, layout_.weeklyLineHeight, layout_.weeklyBarHeight,
                 row.weeklyPercent, withAlpha(row.color, kWeeklyBarAlpha));
        paintText(graphics, formatPercent(row.weeklyPercent) + L" sem", barsLeft, weeklyTop,
                  layout_.weeklyLineHeight, 9 * layout_.scale, kWeeklyTextColor);
    }

    // Vendors without a bundled logo get a dot in their brand color instead.
    void paintLogo(Gdiplus::Graphics& graphics, const PillRow& row, float left, float top) const {
        float size = layout_.logoSize;
        Gdiplus::RectF box(left, top + (layout_.contentHeight() - size) / 2, size, size);
        Gdiplus::SolidBrush brush{Gdiplus::Color(row.color)};
        const BrandLogoShape* logo = findBrandLogo(row.vendorId);
        if (logo == nullptr) {
            box.Inflate(-size / 4, -size / 4);
            graphics.FillEllipse(&brush, box);
            return;
        }
        Gdiplus::GraphicsPath path(Gdiplus::FillModeWinding);
        LogoPathBuilder(box, path).build(*logo);
        graphics.FillPath(&brush, &path);
    }

    void paintBar(Gdiplus::Graphics& graphics, float left, float lineTop, float lineHeight,
                  float barHeight, int percent, Gdiplus::ARGB color) const {
        Gdiplus::RectF track(left, lineTop + (lineHeight - barHeight) / 2, layout_.barWidth,
                             barHeight);
        fillRoundedRect(graphics, kTrackColor, track, barHeight / 2);
        if (percent <= 0) {
            return;
        }
        Gdiplus::RectF fill = track;
        fill.Width = std::max(barHeight, track.Width * percent / 100.0f);
        fillRoundedRect(graphics, color, fill, barHeight / 2);
    }

    void paintText(Gdiplus::Graphics& graphics, const std::wstring& text, float barsLeft,
                   float lineTop, float lineHeight, float fontPixels, Gdiplus::ARGB color) const {
        Gdiplus::Font font(L"Segoe UI", fontPixels, Gdiplus::FontStyleBold, Gdiplus::UnitPixel);
        Gdiplus::SolidBrush brush{Gdiplus::Color(color)};
        Gdiplus::StringFormat format;
        format.SetLineAlignment(Gdiplus::StringAlignmentCenter);
        format.SetFormatFlags(Gdiplus::StringFormatFlagsNoWrap);
        float textLeft = barsLeft + layout_.barWidth + layout_.barGap;
        Gdiplus::RectF rect(textLeft, lineTop, layout_.textWidth, lineHeight);
        graphics.DrawString(text.c_str(), -1, &font, rect, &format, &brush);
    }

    void paintStaleDot(Gdiplus::Graphics& graphics, const DibCanvas& canvas) const {
        float diameter = 4 * layout_.scale;
        Gdiplus::SolidBrush brush{Gdiplus::Color(kStaleDotColor)};
        graphics.FillEllipse(&brush, canvas.width() - diameter - 2 * layout_.scale,
                             2 * layout_.scale, diameter, diameter);
    }

    PillLayout layout_;
};

}  // namespace

// ---- src/pill_window.h ----

namespace {

constexpr UINT_PTR kPlacementTimerId = 1;
constexpr UINT kPlacementPollMs = 2000;
constexpr wchar_t kTaskbarClassName[] = L"Shell_TrayWnd";

// Centers the pill vertically on the taskbar, leftOffsetPixels from its left edge.
// Example: taskbarPillOrigin({0, 1032, 1920, 1080}, {250, 32}, 12) == POINT{12, 1040}
POINT taskbarPillOrigin(RECT taskbar, SIZE pill, int leftOffsetPixels) {
    LONG freeHeight = std::max<LONG>(0, taskbar.bottom - taskbar.top - pill.cy);
    return {taskbar.left + leftOffsetPixels, taskbar.top + freeHeight / 2};
}

// Layered, click-through window drawn over the left end of the taskbar. It is
// owned by the taskbar, so it stays above it without fighting other topmost
// windows. Create and pump it on the same thread; any thread may post
// kSnapshotChangedMsg to it.
// Example: PillWindow window(settings, store); window.create(); PillWindow::runMessageLoop();
class PillWindow {
public:
    PillWindow(const PillSettings& settings, const UsageSnapshotStore& store)
        : settings_(settings), store_(store) {}

    ~PillWindow() {
        if (window_ != nullptr) {
            DestroyWindow(window_);
        }
        UnregisterClassW(kWindowClassName, moduleInstance());
    }

    PillWindow(const PillWindow&) = delete;
    PillWindow& operator=(const PillWindow&) = delete;

    HWND create() {
        registerWindowClass();
        DWORD exStyle = WS_EX_LAYERED | WS_EX_TRANSPARENT | WS_EX_TOPMOST | WS_EX_TOOLWINDOW |
                        WS_EX_NOACTIVATE;
        HWND taskbar = FindWindowW(kTaskbarClassName, nullptr);
        window_ = CreateWindowExW(exStyle, kWindowClassName, L"AI Usage Pill", WS_POPUP, 0, 0, 1, 1,
                                  taskbar, nullptr, moduleInstance(), this);
        if (window_ == nullptr) {
            throwLastError("CreateWindowExW", kWindowClassName);
        }
        SetTimer(window_, kPlacementTimerId, kPlacementPollMs, nullptr);
        repaintSafely();
        ShowWindow(window_, SW_SHOWNOACTIVATE);
        return window_;
    }

    static void runMessageLoop() {
        MSG message;
        while (GetMessageW(&message, nullptr, 0, 0) > 0) {
            TranslateMessage(&message);
            DispatchMessageW(&message);
        }
    }

private:
    // Inside explorer.exe the window belongs to the mod DLL, not to the exe.
    static HINSTANCE moduleInstance() {
        HMODULE module = nullptr;
        GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                               GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                           reinterpret_cast<LPCWSTR>(&PillWindow::windowProc), &module);
        return module;
    }

    static void registerWindowClass() {
        WNDCLASSEXW windowClass{};
        windowClass.cbSize = sizeof(windowClass);
        windowClass.lpfnWndProc = &PillWindow::windowProc;
        windowClass.hInstance = moduleInstance();
        windowClass.lpszClassName = kWindowClassName;
        RegisterClassExW(&windowClass);
    }

    static LRESULT CALLBACK windowProc(HWND window, UINT message, WPARAM wParam, LPARAM lParam) {
        if (message == WM_NCCREATE) {
            CREATESTRUCTW* creation = reinterpret_cast<CREATESTRUCTW*>(lParam);
            SetWindowLongPtrW(window, GWLP_USERDATA,
                              reinterpret_cast<LONG_PTR>(creation->lpCreateParams));
        }
        PillWindow* self = reinterpret_cast<PillWindow*>(GetWindowLongPtrW(window, GWLP_USERDATA));
        if (self == nullptr) {
            return DefWindowProcW(window, message, wParam, lParam);
        }
        return self->handleMessage(window, message, wParam, lParam);
    }

    LRESULT handleMessage(HWND window, UINT message, WPARAM wParam, LPARAM lParam) {
        switch (message) {
            case kSnapshotChangedMsg:
            case WM_DISPLAYCHANGE:
            case WM_DPICHANGED:
            case WM_SETTINGCHANGE:
                repaintSafely();
                return 0;
            case WM_TIMER:
                refreshPlacement();
                return 0;
            case WM_DESTROY:
                window_ = nullptr;
                PostQuitMessage(0);
                return 0;
            default:
                return DefWindowProcW(window, message, wParam, lParam);
        }
    }

    // An exception escaping a window procedure would take explorer.exe down.
    void repaintSafely() {
        try {
            repaint();
        } catch (const std::exception& error) {
            Wh_Log(L"Pill repaint failed: %S", error.what());
        }
    }

    void repaint() {
        if (window_ == nullptr) {
            return;
        }
        UsageSnapshot snapshot = store_.read();
        std::vector<PillRow> rows = buildPillRows(settings_.vendorStyles, snapshot.usages);
        PillLayout layout = PillLayout::forDpi(GetDpiForWindow(window_));
        SIZE size = layout.pillSize(rows.size());
        DibCanvas canvas(size.cx, size.cy);
        PillPainter(layout).paint(canvas, rows, snapshot.stale);
        lastTaskbarRect_ = currentTaskbarRect();
        int leftOffset = static_cast<int>(std::lround(settings_.leftOffset * layout.scale));
        POINT origin = taskbarPillOrigin(lastTaskbarRect_, size, leftOffset);
        present(canvas, origin, opacityByte(snapshot.stale));
    }

    // Polled because the shell sends no message to other windows when the
    // taskbar moves or a fullscreen app starts.
    void refreshPlacement() {
        ShowWindow(window_, isFullscreenAppRunning() ? SW_HIDE : SW_SHOWNOACTIVATE);
        RECT taskbarRect = currentTaskbarRect();
        if (!EqualRect(&taskbarRect, &lastTaskbarRect_)) {
            repaintSafely();
        }
    }

    // Without a taskbar (explorer still starting) the pill uses the bottom
    // strip of the primary monitor, and the next poll moves it into place.
    static RECT currentTaskbarRect() {
        RECT taskbarRect{};
        HWND taskbar = FindWindowW(kTaskbarClassName, nullptr);
        if (taskbar != nullptr && GetWindowRect(taskbar, &taskbarRect)) {
            return taskbarRect;
        }
        MONITORINFO info{sizeof(MONITORINFO)};
        GetMonitorInfoW(MonitorFromPoint({0, 0}, MONITOR_DEFAULTTOPRIMARY), &info);
        return {info.rcMonitor.left, info.rcMonitor.bottom - 48, info.rcMonitor.right,
                info.rcMonitor.bottom};
    }

    static bool isFullscreenAppRunning() {
        QUERY_USER_NOTIFICATION_STATE state = QUNS_ACCEPTS_NOTIFICATIONS;
        if (FAILED(SHQueryUserNotificationState(&state))) {
            return false;
        }
        switch (state) {
            case QUNS_BUSY:
            case QUNS_RUNNING_D3D_FULL_SCREEN:
            case QUNS_PRESENTATION_MODE:
                return true;
            default:
                return false;
        }
    }

    BYTE opacityByte(bool stale) const {
        int percent = stale ? settings_.opacityPercent / 2 : settings_.opacityPercent;
        return static_cast<BYTE>(percent * 255 / 100);
    }

    void present(const DibCanvas& canvas, POINT origin, BYTE alpha) {
        SIZE size{canvas.width(), canvas.height()};
        POINT source{0, 0};
        BLENDFUNCTION blend{AC_SRC_OVER, 0, alpha, AC_SRC_ALPHA};
        UpdateLayeredWindow(window_, nullptr, &origin, &size, canvas.deviceContext(), &source, 0,
                            &blend, ULW_ALPHA);
    }

    const PillSettings& settings_;
    const UsageSnapshotStore& store_;
    HWND window_ = nullptr;
    RECT lastTaskbarRect_{};
};

}  // namespace

// ---- src/pill_app.h ----

namespace {

// Owns the poller and the UI thread. Only one instance runs per logon session,
// because Windhawk injects the mod into every explorer.exe process.
// Example: PillApp app(settings); if (app.start()) { ...; app.stop(); }
class PillApp {
public:
    explicit PillApp(PillSettings settings, std::wstring instanceMutexName = kInstanceMutexName)
        : settings_(std::move(settings)),
          instanceMutexName_(std::move(instanceMutexName)),
          windowReady_(CreateEventW(nullptr, TRUE, FALSE, nullptr)) {}

    ~PillApp() { stop(); }

    PillApp(const PillApp&) = delete;
    PillApp& operator=(const PillApp&) = delete;

    // Returns false when another process already shows the pill.
    bool start() {
        instanceMutex_.reset(CreateMutexW(nullptr, FALSE, instanceMutexName_.c_str()));
        if (instanceMutex_.get() == nullptr || GetLastError() == ERROR_ALREADY_EXISTS) {
            instanceMutex_.reset();
            return false;
        }
        uiThread_ = std::thread(&PillApp::runUiThread, this);
        WaitForSingleObject(windowReady_.get(), 5000);
        poller_ = std::make_unique<UsagePoller>(settings_.command, settings_.refreshMinutes, store_,
                                                [this] { notifyWindow(); });
        poller_->start();
        return true;
    }

    // The poller stops first so nothing posts to the window while it closes.
    void stop() {
        poller_.reset();
        HWND window = window_.exchange(nullptr);
        if (window != nullptr) {
            PostMessageW(window, WM_CLOSE, 0, 0);
        }
        if (uiThread_.joinable()) {
            uiThread_.join();
        }
        instanceMutex_.reset();
    }

private:
    void runUiThread() {
        SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
        try {
            GdiplusSession gdiplus;
            PillWindow window(settings_, store_);
            window_.store(window.create());
            SetEvent(windowReady_.get());
            PillWindow::runMessageLoop();
        } catch (const std::exception& error) {
            Wh_Log(L"Pill window failed: %S", error.what());
            SetEvent(windowReady_.get());
        }
    }

    void notifyWindow() {
        HWND window = window_.load();
        if (window != nullptr) {
            PostMessageW(window, kSnapshotChangedMsg, 0, 0);
        }
    }

    PillSettings settings_;
    std::wstring instanceMutexName_;
    UsageSnapshotStore store_;
    UniqueHandle windowReady_;
    UniqueHandle instanceMutex_;
    std::atomic<HWND> window_{nullptr};
    std::thread uiThread_;
    std::unique_ptr<UsagePoller> poller_;
};

}  // namespace

// ---- src/mod_entry.cpp ----

namespace {

constexpr Gdiplus::ARGB kFallbackVendorColor = 0xFF9CA3AF;

// Reads the Windhawk settings page; empty or invalid fields fall back to the
// defaults so a half-filled settings page still shows a usable pill.
// Example: PillSettings settings = PillSettingsLoader().load();
class PillSettingsLoader {
public:
    PillSettings load() const {
        PillSettings defaults = defaultPillSettings();
        std::wstring command = readSetting(L"command");
        return {command.empty() ? defaults.command : command,
                std::clamp(Wh_GetIntSetting(L"refreshMinutes"), 1, 60),
                std::clamp(Wh_GetIntSetting(L"leftOffset"), 0, 2000),
                std::clamp(Wh_GetIntSetting(L"opacity"), 20, 100),
                readVendorStyles(defaults.vendorStyles)};
    }

private:
    template <typename... FormatArgs>
    static std::wstring readSetting(const wchar_t* settingName, FormatArgs... formatArgs) {
        PCWSTR rawValue = Wh_GetStringSetting(settingName, formatArgs...);
        std::wstring value = rawValue;
        Wh_FreeStringSetting(rawValue);
        return value;
    }

    static std::vector<VendorStyle> readVendorStyles(const std::vector<VendorStyle>& fallback) {
        std::vector<VendorStyle> styles;
        for (int index = 0;; ++index) {
            std::wstring vendorId = readSetting(L"vendors[%d].id", index);
            if (vendorId.empty()) {
                break;
            }
            styles.push_back({vendorId, readVendorColor(index)});
        }
        return styles.empty() ? fallback : styles;
    }

    static Gdiplus::ARGB readVendorColor(int index) {
        std::wstring hexColor = readSetting(L"vendors[%d].color", index);
        try {
            return parseHexColor(hexColor);
        } catch (const std::invalid_argument& error) {
            Wh_Log(L"vendors[%d].color: %S", index, error.what());
            return kFallbackVendorColor;
        }
    }
};

std::unique_ptr<PillApp> g_pillApp;

}  // namespace

BOOL Wh_ModInit() {
    g_pillApp = std::make_unique<PillApp>(PillSettingsLoader().load());
    if (!g_pillApp->start()) {
        Wh_Log(L"Another explorer.exe process already shows the pill");
    }
    return TRUE;
}

void Wh_ModUninit() {
    g_pillApp.reset();
}

void Wh_ModSettingsChanged() {
    Wh_ModUninit();
    Wh_ModInit();
}
