#!/usr/bin/env python3
"""Converts the provider logos in assets/ into src/brand_logo_paths.h.

The mod cannot load SVG at runtime, so each <path d="..."> becomes a flat float
array that LogoPathBuilder replays into a GDI+ path. Only absolute M/L/H/V/C/Z
are supported, which is what the ai-usagebar icons use; anything else stops the
conversion with the offending command.

Usage: tools/svg_to_logo.py   (run from anywhere, rewrites the header)
"""
import re
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
LOGOS = [("kAnthropicLogo", "assets/anthropic.svg"), ("kOpenaiLogo", "assets/openai.svg")]
MOVE, LINE, CUBIC, CLOSE = 0, 1, 2, 3
TOKEN = re.compile(r"[A-Za-z]|-?(?:\d+\.?\d*|\.\d+)(?:[eE]-?\d+)?")
ARG_COUNT = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6, "Z": 0}


def read_path_data(svg_path: Path) -> str:
    match = re.search(r'<path[^>]*\sd="([^"]+)"', svg_path.read_text())
    if not match:
        raise ValueError(f"{svg_path}: expected one <path d=...>, found none")
    return match.group(1)


def split_commands(path_data: str) -> list[tuple[str, list[float]]]:
    tokens = TOKEN.findall(path_data)
    commands, index, letter = [], 0, None
    while index < len(tokens):
        if tokens[index].isalpha():
            letter = tokens[index]
            index += 1
        if letter not in ARG_COUNT:
            raise ValueError(f"path command {letter!r} rejected; expected one of {''.join(ARG_COUNT)}")
        count = ARG_COUNT[letter]
        commands.append((letter, [float(value) for value in tokens[index:index + count]]))
        index += count
        letter = "L" if letter == "M" else letter
    return commands


def to_floats(commands: list[tuple[str, list[float]]]) -> list[float]:
    floats, current = [], (0.0, 0.0)
    for letter, args in commands:
        if letter == "H":
            letter, args = "L", [args[0], current[1]]
        elif letter == "V":
            letter, args = "L", [current[0], args[0]]
        opcode = {"M": MOVE, "L": LINE, "C": CUBIC, "Z": CLOSE}[letter]
        floats += [opcode, *args]
        current = (args[-2], args[-1]) if args else current
    return floats


def format_array(name: str, floats: list[float]) -> str:
    values = [f"{value:g}" for value in floats]
    values = [value if "." in value or "e" in value else value + ".0" for value in values]
    values = [value + "f" for value in values]
    lines = [", ".join(values[start:start + 12]) for start in range(0, len(values), 12)]
    return f"constexpr float {name}[] = {{\n    " + ",\n    ".join(lines) + "};\n"


def main() -> None:
    arrays = [format_array(name, to_floats(split_commands(read_path_data(PROJECT_DIR / svg))))
              for name, svg in LOGOS]
    header = ("#pragma once\n#include \"common.h\"\n\n"
              "// Generated by tools/svg_to_logo.py from assets/*.svg (ai-usagebar icons, MIT).\n"
              "// Do not edit; change the SVG and rerun the script. 100x100 viewBox.\n\n"
              "namespace {\n\n" + "\n".join(arrays) + "\n}  // namespace\n")
    (PROJECT_DIR / "src/brand_logo_paths.h").write_text(header)
    print("wrote src/brand_logo_paths.h")


if __name__ == "__main__":
    main()
