// ==WindhawkMod==
// @id              ai-usage-pill
// @name            AI Usage Pill
// @description     Pílula na borda esquerda da tela com o uso de sessão e semanal do Claude, Codex e outros, via ai-usagebar
// @version         1.0.0
// @author          gustavofrdev
// @github          https://github.com/gustavofrdev
// @include         explorer.exe
// @architecture    x86-64
// @compilerOptions -lgdiplus -lgdi32 -lshell32 -lruntimeobject -lole32 -loleaut32
// ==/WindhawkMod==

// ==WindhawkModReadme==
/*
# AI Usage Pill

Mostra uma pílula pequena, colada na borda esquerda do monitor principal, com
o uso de cada provedor de IA: a barra grossa é a sessão de 5 horas e a fina é
a semanal. A cor é a da marca (Claude laranja, Codex verde).

Os números vêm do [ai-usagebar](https://github.com/akitaonrails/ai-usagebar).
Por padrão o mod roda o ai-usagebar de dentro do WSL, então usa o login que
já existe lá. Se instalar a versão Windows, troque o comando nas configurações.

A pílula não recebe clique: o mouse passa através dela. Quando a atualização
falha, ela fica apagada com um ponto âmbar e mantém os últimos números; o
motivo aparece no log do mod.
*/
// ==/WindhawkModReadme==

// ==WindhawkModSettings==
/*
- command: wsl.exe -e sh -lc "ai-usagebar usage --json"
  $name: Comando
  $description: Comando que imprime o JSON do ai-usagebar (usage --json). O padrão roda o ai-usagebar do WSL por um shell de login, para achar o ~/.local/bin no PATH. Com a versão Windows, informe o caminho do ai-usagebar.exe seguido de usage --json.
- refreshMinutes: 5
  $name: Intervalo de atualização (minutos)
  $description: Os endpoints da Anthropic e da OpenAI bloqueiam consultas com menos de 5 minutos de intervalo; abaixo disso os números podem ficar mais atrasados, não menos.
- leftOffset: 12
  $name: Distância da esquerda (px)
  $description: Espaço entre a borda esquerda da taskbar e a pílula, em pixels de tela a 100% de escala. Aumente se ela cobrir algo da taskbar.
- opacity: 100
  $name: Opacidade (%)
- vendors:
  - - id: anthropic
      $name: Provedor
    - color: "#D97757"
      $name: Cor
  - - id: openai
      $name: Provedor
    - color: "#10A37F"
      $name: Cor
  $name: Provedores
  $description: Ordem e cor de cada linha. Use o id do ai-usagebar (anthropic, openai, cursor, copilot...).
*/
// ==/WindhawkModSettings==

// Generated by tools/bundle.sh from src/. Edit the files in src/, not this one.

#include <windows.h>
#include <gdiplus.h>
#include <shellapi.h>
#undef GetObject
#include <winrt/Windows.Data.Json.h>
#include <winrt/Windows.Foundation.Collections.h>

#include <algorithm>
#include <atomic>
#include <cmath>
#include <functional>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
